  
version: '3'

services:  
  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
      - 15432:15432
      - 25432:25432
    environment:
      - CUBEJS_DEV_MODE=true
    networks:
      - retecondivisa
    volumes:
      - .:/cube/conf
 
networks:
  retecondivisa:
    driver: bridge
    external: true